# Generated by Django 4.1.1 on 2022-09-30 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('blog_image', models.FileField(blank=True, null=True, upload_to='images')),
                ('blog_category', models.CharField(choices=[('Mental Health', 'Mental Health'), ('Heart Disease', 'Heart Disease'), ('COVID19', 'COVID19'), ('Immunization', 'Immunization')], max_length=100)),
                ('summary', models.TextField(max_length=255)),
                ('content', models.TextField(max_length=255)),
                ('is_draft', models.BooleanField(default=True, verbose_name='Is Draft?')),
                ('myuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
