# Generated by Django 4.1.1 on 2022-10-03 05:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_date', models.DateField()),
                ('app_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('speciality', models.CharField(choices=[('Orthopedics', 'Orthopedics'), ('Obstetrics and Gynecology', 'Obstetrics and Gynecology'), ('Dermatology', 'Dermatology'), ('Pediatrics', 'Pediatrics'), ('Internal Medicine', 'Internal Medicine')], max_length=100)),
                ('doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_doctor', to=settings.AUTH_USER_MODEL)),
                ('patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
